apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: openslice
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/osmysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openslice
  creationTimestamp: null
  labels:
    io.openslice.service: mysql
  name: mysql-portal-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
