apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: openslice
  name: oasapi-pv-volume
  labels:
    type: local
spec:
  storageClassName: oasapi-pv-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/oasapi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openslice
  creationTimestamp: null
  labels:
    io.openslice.service: oasapi-claim0
  name: oasapi-claim0
spec:
  storageClassName: oasapi-pv-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
