apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: openslice
  name: osom-pv-volume
  labels:
    type: local
spec:
  storageClassName: osom-pv-manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/osom"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openslice
  creationTimestamp: null
  labels:
    io.openslice.service: osom-claim0
  name: osom-claim0
spec:
  storageClassName: osom-pv-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
