apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openslice
  labels:
    io.openslice.service: osom
  name: osom
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: osom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/back: "true"
        io.kompose.network/front: "true"
        io.openslice.service: osom
    spec:
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.activemq.brokerUrl": "tcp://anartemis:61616?jms.watchTopicAdvisories=false", "spring.activemq.user": "artemis", "spring.activemq.password": "artemis", "logging.level.org.springframework" : "INFO" }'
          image: openslice/io.openslice.osom:latest
          name: openslice-osom
          ports:
            - containerPort: 13100
          volumeMounts:
            - mountPath: /root
              name: osom-claim0
      restartPolicy: Always
      volumes:
        - name: osom-claim0
          persistentVolumeClaim:
            claimName: osom-claim0
---
apiVersion: v1
kind: Service
metadata:
  namespace: openslice
  labels:
    io.openslice.service: osom
  name: osom
spec:
  ports:
    - targetPort: 13100
      port: 13100
  selector:
    io.openslice.service: osom
