apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openslice
  labels:
    io.openslice.service: osportalapi
  name: osportalapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: osportalapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/back: "true"
        io.kompose.network/front: "true"
        io.openslice.service: osportalapi
    spec:
      initContainers:
      - name: init-keycloak
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup keycloak; do echo waiting for keycloak; sleep 2; done"]
      - name: init-mysql-portal
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for mysql; sleep 2; done"]
      containers:
        - env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "spring.datasource.url": "jdbc:mysql://mysql/osdb?createDatabaseIfNotExist=true", "spring.datasource.username":"root", "spring.datasource.password":"letmein", "keycloak-internal-auth-server-url": "http://keycloak/auth", "keycloak-admin-password": "Pa55w0rd", "keycloak.auth-server-url": "http://keycloak/auth", "spring.activemq.brokerUrl": "tcp://activemq:61616", "spring.activemq.user": "admin", "spring.activemq.password": "admin", "spring.cloud.consul.host": "http://consul", "spring.cloud.consul.discovery.healthCheckUrl" : "http://osportalapi/osapi/actuator/health", "swagger.authserver" : "http://INGRESSADDR/auth/realms/openslice", "swagger.clientid" : "osapiWebClientId", "swagger.clientsecret" : "secret", "logging.level.org.springframework" : "INFO" }'
          image: openslice/io.openslice.portal.api:latest
          name: openslice-portalapi
          ports:
            - containerPort: 13000
          volumeMounts:
            - mountPath: /root
              name: osportalapi-claim0
      restartPolicy: Always
      volumes:
        - name: osportalapi-claim0
          persistentVolumeClaim:
            claimName: osportalapi-claim0
---
apiVersion: v1
kind: Service
metadata:
  namespace: openslice
  labels:
    io.openslice.service: osportalapi
  name: osportalapi
spec:
  ports:
    - port: 13000
      targetPort: 13000
  selector:
    io.openslice.service: osportalapi
