apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openslice
  labels:
    io.openslice.service: portainer
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.openslice.service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/front: "true"
        io.openslice.service: portainer
    spec:
      containers:
        - image: portainer/portainer-ce:2.18.4
          name: portainer
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: portainer-claim0
            - mountPath: /data
              name: portainer-data
      restartPolicy: Always
      volumes:
        - name: portainer-claim0
          persistentVolumeClaim:
            claimName: portainer-claim0
        - name: portainer-data
          persistentVolumeClaim:
            claimName: portainer-data
---
apiVersion: v1
kind: Service
metadata:
  namespace: openslice
  labels:
    io.openslice.service: portainer
  name: portainer
spec:
  ports:
    - targetPort: 9000
      port: 9000
  selector:
    io.openslice.service: portainer
