kind: ConfigMap 
apiVersion: v1 
metadata:
  name: tmfweb-config-nginx
  namespace: openslice
data:
  default.conf: |+
        # Expires map
        map $sent_http_content_type $expires {
            default                    off;
            text/html                  epoch;
            text/css                   max;
            application/json           max;
            application/javascript     max;
            ~image/                    max;
        }

        server {
                listen 80;
                include /etc/nginx/mime.types;

          server_name  localhost;
          location / {
              root /usr/share/nginx/html/services;
              index index.html index.htm;
              try_files $uri $uri/ /index.html =404;
            }

          expires $expires;
          gzip  on;
        }
