apiVersion: apps/v1
kind: Deployment
metadata:	
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: centrallog
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ include "openslice.fullname" . }}-centrallog
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "openslice.fullname" . }}
      io.openslice.service: centrallog
      {{- include "openslice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "openslice.fullname" . }}
        io.openslice.service: centrallog
        {{- include "openslice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.centrallog.repository }}:{{ .Values.image.centrallog.tag | default .Chart.AppVersion }}"
          name: {{ include "openslice.fullname" . }}-centrallog
          env:
            - name: SPRING_APPLICATION_JSON
              value: >-
                { 
                  "spring.activemq.brokerUrl": "tcp://{{ include "openslice.fullname" . }}-artemis:61616?jms.watchTopicAdvisories=false", 
                  "spring.activemq.user": "{{ .Values.oscreds.activemq.user }}", 
                  "spring.activemq.password": "{{ .Values.oscreds.activemq.password }}", 
                  "centrallogurl": "{{ .Values.centrallogurl }}"
                }
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 13013
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: centrallog
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ include "openslice.fullname" . }}-centrallog
spec:
  ports:
    - name: "13013"
      targetPort: 13013
      port: 13013
  selector:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: centrallog
    {{- include "openslice.selectorLabels" . | nindent 4 }}

