apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: keycloak
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ include "openslice.fullname" . }}-keycloak-realm-config
  namespace: {{ .Release.Namespace }}
data:
  realm-export.json: |
    {{- (.Files.Get "files/realm-export.json") | toYaml | nindent 4 }}
