apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: osom
    type: local
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ include "openslice.fullname" . }}-osom-pv-volume
spec:
  storageClassName: "osom-pv-manual"
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/osom"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: osom
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ include "openslice.fullname" . }}-osom-claim0
spec:
  storageClassName: "osom-pv-manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
