apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: osportalapi
    type: local
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ include "openslice.fullname" . }}-osportalapi-pv-volume
spec:
  storageClassName: "osportalapi-pv-volume"
  capacity:
    storage: "100Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/dockerdata-nfs/osportalapi-pv-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "openslice.fullname" . }}
    io.openslice.service: osportalapi
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    {{- include "openslice.labels" . | nindent 4 }}
  name: {{ include "openslice.fullname" . }}-osportalapi-claim0
spec:
  storageClassName: "osportalapi-pv-volume"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
